apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\DEVOPS\FINAL PROJECT\text-generation-webui\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: text-generation-webui
  name: text-generation-webui
spec:
  ports:
    - name: "7860"
      port: 7860
      targetPort: 7860
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: text-generation-webui
status:
  loadBalancer: {}
